version: '3.8'

services:
  nestapp:
    build: ./
    ports:
      - 3001:3000
    depends_on:
      - postgresdb
    env_file:
      - .env

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: